# Generated by Django 3.0.2 on 2020-01-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('exp_id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('present', models.BooleanField()),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('home_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('avatar', models.ImageField(upload_to='')),
                ('resume', models.FileField(upload_to='')),
            ],
        ),
    ]
